import React, { useState } from 'react';
import { Sparkles, Download, FileText, Settings, BookOpen, Loader2 } from 'lucide-react';
import { GoogleGenAI, Type } from '@google/genai';

const LoadingAnimation = () => (
  <div className="flex flex-col items-center justify-center gap-4 py-12">
    <div className="relative w-24 h-24">
      <div className="absolute inset-0 border-4 border-purple-200 dark:border-purple-900 rounded-full"></div>
      <div className="absolute inset-0 border-4 border-t-purple-600 dark:border-t-purple-400 rounded-full animate-spin"></div>
      <Sparkles className="absolute inset-0 m-auto text-pink-500 animate-pulse" size={32} />
    </div>
    <p className="text-purple-600 dark:text-purple-400 font-medium animate-pulse">กำลังเนรมิต GEM ให้คุณ...</p>
  </div>
);

export const GemMaker = () => {
  const [inputPrompt, setInputPrompt] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [result, setResult] = useState<{
    name: string;
    instruction: string;
    howto: string;
  } | null>(null);
  const [error, setError] = useState('');

  const handleGenerate = async () => {
    if (!inputPrompt.trim()) return;
    
    setIsGenerating(true);
    setError('');
    setResult(null);

    try {
      // Initialize Gemini API
      const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });
      
      const prompt = `You are an expert Prompt Engineer and Business Logic Consultant. 
The user wants to create a custom AI system (GEM/GPTs) for the following task: "${inputPrompt}"

Please generate a complete package for this custom AI system.
Return the result as a JSON object with the following structure:
{
  "name": "A professional and catchy name for this GEM/GPTs",
  "instruction": "The complete, powerful Custom Instruction (System Prompt) that includes expert business logic, frameworks, and step-by-step processing rules.",
  "howto": "A step-by-step guide on how the end-user should use this GEM/GPTs effectively."
}

Ensure the output is in Thai language.`;

      const response = await ai.models.generateContent({
        model: 'gemini-3-flash-preview',
        contents: prompt,
        config: {
          responseMimeType: 'application/json',
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              name: { type: Type.STRING, description: 'Name of the GEM/GPTs' },
              instruction: { type: Type.STRING, description: 'Custom Instruction / System Prompt' },
              howto: { type: Type.STRING, description: 'How to use guide' }
            },
            required: ['name', 'instruction', 'howto']
          }
        }
      });

      if (response.text) {
        const parsedResult = JSON.parse(response.text);
        setResult(parsedResult);
      } else {
        throw new Error('No response from AI');
      }
    } catch (err) {
      console.error('Generation error:', err);
      setError('เกิดข้อผิดพลาดในการสร้าง GEM กรุณาลองใหม่อีกครั้ง');
    } finally {
      setIsGenerating(false);
    }
  };

  const handleDownloadDoc = () => {
    if (!result) return;

    // Create HTML content that MS Word can interpret
    const htmlContent = `
      <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
      <head>
        <meta charset='utf-8'>
        <title>${result.name}</title>
        <style>
          body { font-family: 'Sarabun', 'Cordia New', sans-serif; line-height: 1.6; color: #333; }
          h1 { color: #4f46e5; border-bottom: 2px solid #4f46e5; padding-bottom: 10px; }
          h2 { color: #ec4899; margin-top: 20px; }
          .section { margin-bottom: 20px; padding: 15px; background-color: #f9fafb; border: 1px solid #e5e7eb; border-radius: 8px; }
          .footer { margin-top: 40px; font-size: 12px; color: #6b7280; text-align: center; border-top: 1px solid #e5e7eb; padding-top: 10px; }
          pre { white-space: pre-wrap; font-family: inherit; }
        </style>
      </head>
      <body>
        <h1>💎 ${result.name}</h1>
        
        <div class="section">
          <h2>⚙️ Custom Instruction (System Prompt)</h2>
          <pre>${result.instruction}</pre>
        </div>
        
        <div class="section">
          <h2>📖 วิธีใช้งาน (How-to)</h2>
          <pre>${result.howto}</pre>
        </div>
        
        <div class="footer">
          Generated by GEM Maker (Modgoscale Logic)
        </div>
      </body>
      </html>
    `;

    const blob = new Blob(['\ufeff', htmlContent], {
      type: 'application/msword'
    });
    
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${result.name.replace(/[^a-z0-9ก-๙]/gi, '_')}_GEM.doc`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="max-w-4xl mx-auto animate-[animationIn_0.4s_ease-out_both]">
      {/* Header Section */}
      <div className="text-center mb-12">
        <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-purple-100 dark:bg-purple-900/30 text-purple-600 dark:text-purple-400 font-medium text-sm mb-6">
          <Sparkles size={16} />
          <span>Feature: GEM Maker</span>
        </div>
        <h2 className="text-3xl sm:text-4xl font-bold text-gray-900 dark:text-white mb-4">
          เปลี่ยนไอเดียในหัว ให้กลายเป็นระบบ AI<br className="hidden sm:block" /> พร้อมใช้ใน 30 วินาที
        </h2>
        <p className="text-lg text-gray-600 dark:text-gray-400 max-w-2xl mx-auto">
          ไม่ต้องปวดหัวกับการเขียน Prompt ยาวๆ อีกต่อไป เพราะ GEM Maker จะทำหน้าที่เป็น Prompt Engineer ส่วนตัวที่ช่วยเนรมิตระบบ AI ให้คุณจากความว่างเปล่า ด้วย Business Logic ระดับผู้เชี่ยวชาญที่คุณวางใจได้ค่ะ
        </p>
      </div>

      {/* 3 Steps */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-12">
        <div className="bg-white dark:bg-gray-800 rounded-2xl p-6 shadow-sm border border-gray-100 dark:border-gray-700">
          <div className="w-12 h-12 bg-blue-100 dark:bg-blue-900/30 text-blue-600 dark:text-blue-400 rounded-xl flex items-center justify-center text-xl font-bold mb-4">1</div>
          <h3 className="text-lg font-bold text-gray-900 dark:text-white mb-2">Input: บอกโจทย์ที่คุณต้องการ ✍️</h3>
          <p className="text-sm text-gray-600 dark:text-gray-400">แค่กรอกความต้องการสั้นๆ ว่าอยากให้ AI ช่วยงานเรื่องอะไร (เช่น 'อยากได้ GEM ช่วยวิเคราะห์จุดคุ้มทุนของโปรเจกต์ใหม่')</p>
        </div>
        <div className="bg-white dark:bg-gray-800 rounded-2xl p-6 shadow-sm border border-gray-100 dark:border-gray-700">
          <div className="w-12 h-12 bg-purple-100 dark:bg-purple-900/30 text-purple-600 dark:text-purple-400 rounded-xl flex items-center justify-center text-xl font-bold mb-4">2</div>
          <h3 className="text-lg font-bold text-gray-900 dark:text-white mb-2">Process: ผสมผสาน Logic อัจฉริยะ 🧠</h3>
          <p className="text-sm text-gray-600 dark:text-gray-400">ระบบจะนำโครงสร้างทางความคิด (Framework) ที่ผ่านการกลั่นกรองมาแล้ว ไปประกอบร่างกับโจทย์ของคุณทันที</p>
        </div>
        <div className="bg-white dark:bg-gray-800 rounded-2xl p-6 shadow-sm border border-gray-100 dark:border-gray-700">
          <div className="w-12 h-12 bg-pink-100 dark:bg-pink-900/30 text-pink-600 dark:text-pink-400 rounded-xl flex items-center justify-center text-xl font-bold mb-4">3</div>
          <h3 className="text-lg font-bold text-gray-900 dark:text-white mb-2">Instant Output: รับ Full Package 📄</h3>
          <p className="text-sm text-gray-600 dark:text-gray-400">รับชุดคำสั่งที่สมบูรณ์ที่สุด พร้อมชื่อ, Custom Instruction, วิธีใช้ และสามารถ Export เป็นไฟล์ Docs ได้ทันที</p>
        </div>
      </div>

      {/* Input Section */}
      <div className="bg-white dark:bg-gray-900 rounded-3xl p-6 sm:p-8 shadow-xl shadow-gray-200/50 dark:shadow-black/20 border border-gray-200 dark:border-gray-800 mb-8">
        <label className="block text-lg font-medium text-gray-900 dark:text-white mb-4">
          คุณอยากให้ AI ช่วยงานเรื่องอะไร?
        </label>
        <textarea
          value={inputPrompt}
          onChange={(e) => setInputPrompt(e.target.value)}
          placeholder="เช่น อยากได้ GPTs ช่วยร่างสคริปต์ปิดการขายทางโทรศัพท์..."
          className="w-full h-32 px-4 py-3 rounded-2xl border border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-800 text-gray-900 dark:text-white focus:ring-2 focus:ring-purple-500 outline-none transition-all resize-none mb-4"
        />
        {isGenerating ? (
          <LoadingAnimation />
        ) : (
          <button
            onClick={handleGenerate}
            disabled={isGenerating || !inputPrompt.trim()}
            className="w-full sm:w-auto px-8 py-3.5 bg-gradient-to-r from-purple-600 to-pink-500 hover:from-purple-700 hover:to-pink-600 text-white rounded-xl font-medium shadow-lg shadow-purple-500/25 transition-all hover:-translate-y-0.5 disabled:opacity-50 disabled:cursor-not-allowed disabled:transform-none flex items-center justify-center gap-2"
          >
            <Sparkles size={20} />
            สร้าง GEM ของฉันเลย!
          </button>
        )}
        {error && <p className="text-red-500 mt-4 text-sm">{error}</p>}
      </div>

      {/* Output Section */}
      {result && (
        <div className="bg-white dark:bg-gray-900 rounded-3xl p-6 sm:p-8 shadow-xl shadow-gray-200/50 dark:shadow-black/20 border border-purple-200 dark:border-purple-900/50 animate-[animationIn_0.5s_ease-out_both]">
          <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 mb-8">
            <h3 className="text-2xl font-bold text-gray-900 dark:text-white flex items-center gap-3">
              <span className="text-3xl">💎</span> {result.name}
            </h3>
            <button
              onClick={handleDownloadDoc}
              className="px-5 py-2.5 bg-gray-900 dark:bg-white text-white dark:text-gray-900 rounded-xl font-medium shadow-md hover:shadow-lg transition-all hover:-translate-y-0.5 flex items-center gap-2 whitespace-nowrap"
            >
              <Download size={18} />
              Download as Doc
            </button>
          </div>

          <div className="space-y-6">
            <div className="bg-gray-50 dark:bg-gray-800/50 rounded-2xl p-6 border border-gray-200 dark:border-gray-700">
              <h4 className="text-lg font-bold text-gray-900 dark:text-white mb-4 flex items-center gap-2">
                <Settings className="text-purple-500" size={20} />
                ⚙️ Custom Instruction
              </h4>
              <pre className="whitespace-pre-wrap font-mono text-sm text-gray-800 dark:text-gray-200 leading-relaxed bg-white dark:bg-gray-900 p-4 rounded-xl border border-gray-100 dark:border-gray-800">
                {result.instruction}
              </pre>
            </div>

            <div className="bg-gray-50 dark:bg-gray-800/50 rounded-2xl p-6 border border-gray-200 dark:border-gray-700">
              <h4 className="text-lg font-bold text-gray-900 dark:text-white mb-4 flex items-center gap-2">
                <BookOpen className="text-pink-500" size={20} />
                📖 วิธีใช้งาน (How-to)
              </h4>
              <pre className="whitespace-pre-wrap font-sans text-sm text-gray-800 dark:text-gray-200 leading-relaxed bg-white dark:bg-gray-900 p-4 rounded-xl border border-gray-100 dark:border-gray-800">
                {result.howto}
              </pre>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
